### ISSUE TITLE
Windows Defender quarantines the assembly

### ISSUE THREAD

**Issue by i-ghost** [bchavez/Bogus#211] opened 2019-03-21 11:36 UTC
Hi,

During a deployment of a site using this package to a Windows server, we noticed that Windows Defender quarantines the assembly as a `Trojan:Win32/Skeeyah.I`. [VirusTotal shows the same.](https://www.virustotal.com/#/file/1f86252131eb393b885e7f1a5e8bb62a713862acece28f7ad9566e380db6dd82/details) I assume this is a false positive?

**Comment by jasonwurzel** [comment] 2019-03-21 12:38
Since today I got the same complaint from Defender. It started after the Defender definition update today. It is only the latest release (26.0.1) and only Defender complaints (checking several scanners via VirusTotal).

**Comment by i-ghost** [comment] 2019-03-21 13:11
As a workaround to keep your deploys working, if you're using PowerShell in your deployment pipeline you can whitelist your deployment target directory using:

`Add-MpPreference -ExclusionPath "C:\Path\to\site"`

**Comment by bchavez** [comment] 2019-03-21 15:33
Hey there,

That's pretty strange. It should obviously be a false positive. I tested the latest Defender definitions and all seems okay here on Windows 7. Bogus.dll (26.0.1) didn't get quarantined.

![msseces_2843](https://user-images.githubusercontent.com/478118/54763542-65c2b880-4bb3-11e9-9d4b-968cf4b1c4b7.png)

* What operating system are you using?
* What virus definition version are you using with Windows Defender?

I'll try to get someone from Microsoft Security to help or give more info.

/cc @blowdart

**Comment by bchavez** [comment] 2019-03-21 15:49
Also, as a sanity check could you double check the assembly signature of `Bogus.dll` with the `sn.exe` strong-name utility just to make sure you have nothing bad is attaching itself to the DLL.

```
R:\bogus.26.0.1\lib\net40>sn -vf Bogus.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'Bogus.dll' is valid

R:\bogus.26.0.1\lib\netstandard1.3>sn -vf Bogus.dll

Assembly 'Bogus.dll' is valid

R:\bogus.26.0.1\lib\netstandard2.0>sn -vf Bogus.dll

Assembly 'Bogus.dll' is valid

R:\bogus.26.0.1\lib\net40>sn -Tp Bogus.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key (hash algorithm: sha1):
0024000004800000940000000602000000240000525341310004000001000100d981a0be5616f4
50cc0528f88cf96e7bb782edb8ea9a06517cc42b340cdd644a931aab0c7c4902c129eff3d09a3f
8c331026286d55c36f225f33f4709be9352fdf16c7b6781652528c2b77063f19a6ab21ee79368f
552f60da8f503832e2d6ab6aafce934cc8736c24fd391ac286aa14dd5b5959fa546eb25841e41c
fb625aa2

Public key token is fa1bb3f3f218129a
```

**Comment by bchavez** [comment] 2019-03-21 16:07
Checked `net40`, `netstandard1.3` and `netstandard2.0` DLLs and seems like the `netstandard2.0` DLL is the only DLL that's getting flagged:

:heavy_check_mark: `bogus.26.0.1/net40/Bogus.dll`
https://www.virustotal.com/#/file/3b0e7d618d66085da421d3b93bfdf7ba6694a5390643bdb959c5016475db9e56/detection

:heavy_check_mark: `bogus.26.0.1/netstandard1.3/Bogus.dll`
https://www.virustotal.com/#/file/cc6275ac9be3a33199228cb063d9758cd74883ccb920317a94202276103fecd5/detection

:x: `bogus.26.0.1/netstandard2.0/Bogus.dll`
https://www.virustotal.com/#/file/1f86252131eb393b885e7f1a5e8bb62a713862acece28f7ad9566e380db6dd82/detection

**Comment by mikebridge** [comment] 2019-03-21 17:04
I have this on Windows 10 as well:

```

**Comment by i-ghost** [comment] 2019-03-21 17:15
Operating system: Windows Server 2016, version 1607 build 14393.2759.

Virus definition version: 1.289.1716.0

**Comment by bchavez** [comment] 2019-03-21 17:15
Okay friends, I tested:

* Windows 7 64-bit - Windows Defender, latest definitions, `1.289.1745.0`
* Windows 10 64-bit - Windows Defender, latest definitions, `1.289.1745.0`
* Windows Server 2016 - Windows Defender, latest definitions:
    
   ![server2016_2845](https://user-images.githubusercontent.com/478118/54770872-5c404d00-4bc1-11e9-8879-0fad61d7dc2f.png)


And I'm not able to reproduce the issue.

I did received word from Mr. Dorrans, he says to submit the DLLs for rescan here: https://www.microsoft.com/en-us/wdsi/filesubmission

So, I resubmitted the extracted the Bogus NuGet `lib` folder from the NuGet package ([Bogus_v26_0_1.zip](https://github.com/bchavez/Bogus/files/2993126/Bogus_v26_0_1.zip) here), for re-scanning and nothing is getting flagged.

![chrome_2846](https://user-images.githubusercontent.com/478118/54771083-cc4ed300-4bc1-11e9-884a-ee1399bbf97d.png)

Re-ran the analysis at Virus Total, and the false-positive is no longer being flagged by Windows Defender. Here is the re-ran analysis for the `bogus.26.0.1/netstandard2.0/Bogus.dll` DLL at Virus Total. See @i-ghost 's [original link](https://github.com/bchavez/Bogus/issues/211#issue-423686355): 

https://www.virustotal.com/#/file/1f86252131eb393b885e7f1a5e8bb62a713862acece28f7ad9566e380db6dd82/details

```
SHA-256 | 1f86252131eb393b885e7f1a5e8bb62a713862acece28f7ad9566e380db6dd82
```

![chrome_2848](https://user-images.githubusercontent.com/478118/54771331-41baa380-4bc2-11e9-9c23-1dff46f8a3b5.png)

**Comment by i-ghost** [comment] 2019-03-21 17:18
@bchavez That's great news. Thanks for the quick turnaround. I'll get our definitions updated.

**Comment by bchavez** [comment] 2019-03-21 17:30
@i-ghost , thank you for your version information. Please let us know if updating the definition file from `1.289.1716.0` to `1.289.1745.0` works for you.

**Comment by bchavez** [comment] 2019-03-21 20:30
Just got the completed re-scan details via email: ***"We have removed the detection."***


## Submission details 

### bogus_v26_0_1.zip
**Submission ID:** d4c0b938-2f7d-4631-81c6-9f026a77432a
**Status:** Completed
**Submitted by:** bchavez@bitarmory.com
**Submitted:** Mar 21, 2019 9:47:02 AM
**User Opinion:** Incorrect detection

Analyst comments:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run “MpCmdRun.exe -SignatureUpdate” 

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

![chrome_2851](https://user-images.githubusercontent.com/478118/54782895-3a54c380-4bdd-11e9-9b5a-45c7f65ccee9.png)

**Comment by jasonwurzel** [comment] 2019-03-22 09:48
Thank you from me as well, sorry I couldn't provide Info from my side as I was in hibernation at the time ;-)

**Comment by bchavez** [comment] 2019-03-22 19:09
Hey friends,

It looks like we haven't received any new reports of others encountering the issue. The issue seems to be resolved now, so I'm going to close the issue.

I'll be releasing a new version soon with some minor API updates to the `Person` class from feedback I got on twitter. 

If anyone continues to have false-positives with Windows Defender, please feel free to let me know by making a comment and re-opening the issue.

Thanks again for everyone's help.
Brian

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Closed by bchavez** 2019-03-22 19:09 UTC
