### ISSUE TITLE
Faking Lists Within Lists

### ISSUE THREAD

**Issue by rareitchproject** [bchavez/Bogus#135] opened 2018-03-20 17:07 UTC
Hello

I'm having a problem generating a list inside an object.  The elements inside the list must all have unique Guids.  If anybody could offer some advice I'd be very grateful.

Some code. 

I generate 100 contracts, faked like this -
```
var fakeContract = await GenerateContract();
var contractRequests = fakeContract.Generate(100);
private static async Task<Faker<Contract>> GenerateContract()
{
   Supplier supplier = await GetRandomSupplier();
   Ancillary ancillary = await GetRandomAncillary();
   var fakeContract = new Faker<Contract>()
            .Rules((f, o) =>
            {
                o.BaseContractId =  f.Random.Uuid();
                o.ContractDescription = f.Lorem.Random.Words(3);
                //o.Id = contractId;
                o.NetCostsCurrencyCode = f.PickRandom(_currencyCode);
                o.PublicCostsCurrencyCode = f.PickRandom(_currencyCode);
                o.ActivatedDatetime = null;
                o.Status = Status.Live;
                o.SupplierName = supplier.Name;
                o.SupplierOfficeId = supplier.SupplierOffices.Select(s => s.Id).FirstOrDefault();
                o.SupplierOfficeName = supplier.SupplierOffices.Select(s => s.OfficeName).FirstOrDefault();
                o.TermsAndConditionsFileUrl = null;
                o.ValidFrom = DateTime.Now;
                o.ValidTo = DateTime.Now.AddDays(21);
        //      o**.ContractAncillaries** = fakeContractAncillary.Generate(1).ToList();
            });
   var fakeContractAncillary = GenerateContractAncillary(fakeContract, ancillary);
   fakeContract.RuleFor(u => u.ContractAncillaries, fakeContractAncillary.Generate(1).ToList());
}
```
A Contract has a list of ContractAncillaries.
Each Contract will have 1 or many ContractAncillaries and each ContractAncillary must have a unique Guid per ancillary.

At the moment when I generate the fakeContractAncillary, every ContractAncillary has the same Id.
```
private static Faker<ContractAncillary> GenerateContractAncillary(Faker<Contract> fakeContract, Ancillary ancillary)
{
    var newContract = (Contract)fakeContract;
    var fakeConditionSettings = GeneratePaxConditionSettings();
    var fakeCosts = GenerateAncillaryCost();
    var fakeContractAncillary = new Faker<ContractAncillary>()
        .Rules((f, o) =>
        {
            o.Id = f.Random.Uuid();
            o.ContractId = newContract.BaseContractId;
            o.AncillaryId = ancillary.Id;
            o.ImageUrl = String.Empty;
            o.DisplayName = f.Commerce.ProductName();
            o.DisplayDescription = f.Commerce.ProductAdjective();
            o.SupplierNameForAncillary = ancillary.Name;
            o.SellWeb = f.PickRandom(new bool[] { true, false });
            o.SellCallCentre = f.PickRandom(new bool[] { true, false });
            o.CompulsoryStyle = f.PickRandom<CompulsoryStyle>();
            o.NonRefundable = f.PickRandom(new bool[] { true, false });
            o.IncludedInDeposit = f.PickRandom(new bool[] { true, false });
            o.Active = true;
            o.ConditionSettings = fakeConditionSettings.Generate(1).ToList();
            o.Costs = fakeCosts.Generate(1).ToList();
            o.Quotas = null;
        });
    return fakeContractAncillary;
}
```
Many thanks

**Comment by bchavez** [comment] 2018-03-20 19:00
Hi @rareitchproject, I have to help a customer at the moment and might take a few days; so my time is somewhat limited. 

At first glance, I don't see anything that pops out. `f.Random.Uuid()` calls `f.Random.Bytes()` under the hood to source deterministic `Guid`s. If this is a real blocker for you, try using `Guid.NewGuid()` in place of `f.Random.Uuid()`. For sure, that will solve your issue for now. But as to why `Uuid()` keeps giving you the same `Guid`, requires a bit more time to investigate than I currently have.

I'll dig more in-depth with your issue soon as I'm done with the customer support issue.

Thanks,
Brian

:crown: :gem: ***["I know everything that shine ain't always gold..."](https://www.youtube.com/watch?v=7xzU9Qqdqww)***

**Comment by bchavez** [comment] 2018-03-21 20:46
Hi @rareitchproject,

Thanks for waiting, I finally had some time to dig a little deeper into your issue.

You might want to try chaning the following line in your code:
```csharp
fakeContract.RuleFor(u => u.ContractAncillaries, fakeContractAncillary.Generate(1).ToList());
```
and use the lambda `Func<Faker, T>` `f=>` parameter as shown below:
```csharp
fakeContract.RuleFor(u => u.ContractAncillaries, f => fakeContractAncillary.Generate(1).ToList());
```
I think what might be happening with your rule is `RuleFor(lambda, object)` is normally used for constants like `.RuleFor(x => x.Age, 35)`. In your code, the CLR will execute `fakeContractAncillary.Generate(1).ToList()` only time, at the time `.RuleFor` is  being **invoked** to sastisfiy the parameter requirement of `.RuleFor(lambda, object)`. This means, `List<ContractAcillary>` object is evaluated as a parameter at the time the `.RuleFor` method was ***invoked***, not necesarily when the object is being populated. `.RuleFor(lambda1, lambda2)` is the correct overload to ensure that `lambda2` is called on every new object creation of `T`.

-----

Also, I distilled your example down to a minimum. In my example, the `ContractAncillaries` each have their own distinct `Id`. So, I'm not able to reproduce the issue. Here's my code that I came up with:

```csharp
[Fact]
public void test_1_to_many()
{
   var foos = ContractFaker().Generate(3);

   console.Dump(foos);
}

private Faker<Contract> ContractFaker()
{
   var ancillaryFaker = AncillaryFaker();

   var contractFaker = new Faker<Contract>()
      .Rules((f, contract) =>
         {
            contract.Id = f.Random.Uuid();
            contract.ContractAncillaries = ContractAncillaryFaker(contract, ancillaryFaker).Generate(1);
         });


   return contractFaker;
}

private Faker<Ancillary> AncillaryFaker()
{
   var ancillaryFaker = new Faker<Ancillary>()
      .Rules((f, ancillary) =>
         {
            ancillary.Id = f.Random.Uuid();
         });

   return ancillaryFaker;
}

private Faker<ContractAncillary> ContractAncillaryFaker(Contract contract, Ancillary ancillary)
{
   var foobarFaker = new Faker<ContractAncillary>()
      .Rules((f, contractAncillary) =>
         {
            contractAncillary.Id = f.Random.Uuid();
            contractAncillary.AncillaryId = ancillary.Id;
            contractAncillary.ContractId = contract.Id;
         });

   return foobarFaker;
}


public class Contract
{
   public Guid Id { get; set; }
   public List<ContractAncillary> ContractAncillaries { get; set; }
}

public class ContractAncillary
{
   public Guid Id { get; set; }
   public Guid ContractId { get; set; }
   public Guid AncillaryId { get; set; }
}

public class Ancillary
{
   public Guid Id { get; set; }
}
```

And the output shows each `ContractAncillary` with thier own `Id`:

```json
{ //CONTRACT
  "Id": "4c9c23da-c4e0-d72d-e3c4-a89617f255b2",
  "ContractAncillaries": [
    {
      "Id": "d4896747-d3e0-9159-98d0-0c19c904efb8",
      "ContractId": "4c9c23da-c4e0-d72d-e3c4-a89617f255b2",
      "AncillaryId": "bd59c865-cda5-44f4-a28e-db17c014d586"
    }
  ]
},
{ //CONTRACT
  "Id": "39a01809-20cf-0d8e-2e58-aa51e81517ce",
  "ContractAncillaries": [
    {
      "Id": "a80d239f-9c74-27b7-d87c-a6872908a882",
      "ContractId": "39a01809-20cf-0d8e-2e58-aa51e81517ce",
      "AncillaryId": "b04e22ee-8068-91d1-6ec7-25d5c0da7a9d"
    }
  ]
},
{ //CONTRACT
  "Id": "a72b3eb8-3eb6-894f-460e-ca07fbb84c53",
  "ContractAncillaries": [
    {
      "Id": "821ca21f-d3af-60e7-d484-6165d2af2b20",
      "ContractId": "a72b3eb8-3eb6-894f-460e-ca07fbb84c53",
      "AncillaryId": "c4b20ddd-6f07-525a-6b27-d7ecd9496866"
    }
  ]
}
```

Hope that helps,
Brian

**Comment by bchavez** [comment] 2018-03-23 18:31
Hi Dean,

I'm going to close this issue and mark it as resolved but feel free to reopen the issue if you continue to have problems or use https://gitter.im/bchavez/Bogus chat.

Thanks,
Brian

**Closed by bchavez** 2018-03-23 18:31 UTC

**Comment by rareitchproject** [comment] 2018-03-26 07:36
Resolved.  Thanks again.
