### ISSUE TITLE
ReactiveExtensions

### ISSUE THREAD

**Issue by grahamehorner** [bchavez/Bogus#117] opened 2017-12-15 17:44 UTC
When using Bogus to generate large amounts of data from multiple instances of Fake<T> ...  GenerateLazy( xxx ).ToObservable( ).Subscription( ... ) blocks the execution until complete preventing the execution of other Fake<T> and Observable subsriptions

**Comment by bchavez** [comment] 2017-12-15 18:08
Hi @grahamehorner ,

You'll have to provide a sample that demonstrates the issue.

I can't ascertain from your issue description if this is 1) a problem with **Bogus**, 2) a problem with your code, or 3) a problem with Rx.net.

If you could please post a sample project, code, or something that I can reproduce that would help a lot.

Thanks,
Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by bchavez** [comment] 2017-12-20 23:18
Hi @grahamehorner ,

Feel free to re-open the issue when you have a sample code/project that reproduces the problem.

For now, going to close this issue because I'm a bit OCD when it comes to keeping issues open too long.

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Closed by bchavez** 2017-12-20 23:18 UTC
