### ISSUE TITLE
License expression in nuget package not set

### ISSUE THREAD

**Issue by garcipat** [bchavez/Bogus#451] opened 2022-11-17 15:42 UTC
### Version Information
| Software                       | Version(s) |
| ------------------------| ---------- |
| Bogus NuGet Package  |   until Current (34.0.2)              |
| .NET Core?                   |    6             |
| Windows OS?              |    10              |
| Visual Studio?              |     2022             |

### What is the expected behavior?

License information is filled in the nuget package

### What is the actual behavior?

Only the License Url is filled and points to the MIT license

### Any possible solutions?
Just fill the License expression field in the nuget spec.

### How do you reproduce the issue?

Get the nuget and inspect the spec file. Also When adding the nuge tpackage

### Can you identify the location in Bogus' source code where the problem exists?
the .csproj file

### If the bug is confirmed, would you be willing to submit a PR?

I'm willing but never did that before.

**Comment by bchavez** [comment] 2022-11-18 00:36
Hi. Could you help me understand why this is a problem?

**Comment by bchavez** [comment] 2024-04-19 23:26
Going through the issues list and cleaning up. Gonna mark this as a duplicate of #499 . Please subscribe to issue #499 for updates.

**Closed by bchavez** 2024-04-19 23:26 UTC
