### ISSUE TITLE
Switch to licence expression rather than  URL

### ISSUE THREAD

**Issue by thompson-tomo** [bchavez/Bogus#537] opened 2024-03-16 22:42 UTC
### Description

The licence expression property should be set to the correct licence type (depending on the repo) as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc. 

### LINQPad Code Example

n/a

### What alternatives have you considered?

accept the url 

### Could you help with a pull-request?

Yes

**Comment by bchavez** [comment] 2024-03-22 02:39
Duplicate of #499 ; please subscribe to that issue for any updates.

**Closed by bchavez** 2024-03-22 02:39 UTC
