### ISSUE TITLE
Slow generation

### ISSUE THREAD

**Issue by TheMouster** [bchavez/Bogus#234] opened 2019-07-05 07:03 UTC
Hi,

Sorry if this is not the right place to ask this, but I couldn't find a better one. Bogus on .NET Core 2.2 is **very** slow at generating data. It's taking well over a second per item for the following... i.e. in excess of 33 seconds for 20 items. My hardware's not that spectacular Core I5 2.4Ghz 16Gb but IMO it should be much, much faster than this. So I feel like there's something I'm missing. I've got other elements that I want to do this with where I want to generate ~10,000 items and possibly up to 100,000 items, I'm a bit concerned that it will take several hours to do, if not longer.

```
var operators = new Bgs.Faker<Operator>()
                .CustomInstantiator(f => new Operator(f.Person.FullName, f.Person.Email, f.Random.Utf16String(20)))
                .Rules((f, o) => o.Id = Guid.NewGuid()).FinishWith((f, o) => Write(".")).Generate(20);
```

The Operator object is a simple EF POCO. Is this considered normal performance or am I doing something wrong? I'm specifically using Bogus to assist with populating my database with a repeatable set of dummy data for testing.

Thanks

**Comment by bchavez** [comment] 2019-07-05 08:36
Hi Greg,

Thanks for asking your question. No. Bogus shouldn't be that slow.

I tested the following code on two machines. The following code generates **100,000** instances of `Operator` on the order of ***seconds***, not minutes or hours:
```csharp
using System;
using System.Diagnostics;
using Bogus;
using static System.Console;

namespace BogusSpeed
{
   class Program
   {
      static void Main(string[] args)
      {
         var sw = Stopwatch.StartNew();
         var operatorFaker = new Faker<Operator>()
            .CustomInstantiator(f => new Operator(f.Person.FullName, f.Person.Email, f.Random.Utf16String(20)))
            .Rules((f, o) =>
               {
                  o.Id = Guid.NewGuid();
               })
            .FinishWith((f, o) =>
               {
                  Write(".");
               });
         sw.Stop();

         WriteLine($"Constructed operatorFaker in {sw.Elapsed}");

         var total = 100_000;
         sw.Restart();
         var ops = operatorFaker.Generate(total);
         sw.Stop();

         WriteLine();
         WriteLine($"Generated {total} in {sw.Elapsed}");
      }
   }

   public class Operator
   {
      public Operator(string fullName, string email, string utf16String)
      {
         this.FullName = fullName;
         this.Email = email;
         this.Utf16String = utf16String;
      }

      public Guid Id { get; set; }

      public string FullName { get; }
      public string Email { get; }
      public string Utf16String { get; }
   }
}
```
1. Core i7, 64GB RAM:
```
R:\BogusSpeed>dotnet run
Constructed operatorFaker in 00:00:00.0706136
.............................................
Generated 100000 in 00:00:21.9618821
```
2. Xeon, 6GB RAM
```
C:\temp\BogusSpeed>dotnet run
Constructed operatorFaker in 00:00:00.0821972
.............................................
Generated 100000 in 00:00:30.7572110
```
In fact, removing the synchronous blocking IO call to `Write(".")` console stream, I get even faster results. Speeds are roughly cut in half by removing the `Console.Write` call:
```
            //.FinishWith((f, o) =>
            //   {
            //      Write(".");
            //   });
```
1. Core i7, 64GB RAM:
```
R:\BogusSpeed>dotnet run
Constructed operatorFaker in 00:00:00.0687592
Generated 100000 in 00:00:11.2984483
``` 
2. Xeon, 6GB RAM
```
C:\temp\BogusSpeed>dotnet run
Constructed operatorFaker in 00:00:00.0877418
Generated 100000 in 00:00:16.8900565

C:\temp\BogusSpeed> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826
```
---------

So, your issue cannot be reproduced on this side. I would recommend testing the same exact code above on your machine and compare results. You should be able to generate 100,000 instances in a few minutes or less on a Core i5.

I suspect your issue might be related to something not related to Bogus by accessing some external resource that's causing the delay. 

[1]:https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

Things you might also want to check:

* Be aware if you're using .NET Core on Linux over SSH, and you're making a blocking `.Write(".")` IO call to write dots on the screen for each generation, that might be slowing down your generation.
* Check your **Task Manager** for any processes that might be consuming 100% of your CPU.
* Use [Process Explorer][1] to display **Context Switch Deltas**. Sometimes processes can consume high amounts of CPU through a very high number of context switches that don't usually register as "%" CPU consumption.
* Make sure you're not making any database calls in the process of generating your `Faker<T>` models.
* Pre-generate your `Faker<T>` models in memory first, then make DB calls to save the models to the database **after** Bogus has generated your data.

I'm going to close the issue for now since I really think this is a problem on your side, but feel free to re-open the issue if you can come up with a sample project that can reproduce the issue.

Thanks,
Brian

:watch: :city_sunset: ***["I just can't wait... I just can't wait... for saturday night..."](https://www.youtube.com/watch?v=ISbXzQz__Rc)***

**Closed by bchavez** 2019-07-05 08:36 UTC

**Comment by bchavez** [comment] 2019-07-05 08:55
Also, what version of Bogus are you using? Are you using a custom build? What is the `Bgs` namespace? an alias?

**Comment by TheMouster** [comment] 2019-07-05 09:15
Hi Brian,

Thanks for the prompt response. It’s just an alias. Unsure why I have it, I think there’s a conflict with my project. I’m not at my PC at the moment so I can’t be sure.

There are no database calls in the generation and in fact I go out of my way to ensure that there’s only a single call at the end of the routine. 

I’ll put together another project and see how it performs there. My existing code pretty much matches yours so performance should be similar. It’s a puzzle. I’ll let you know how I get on.

**Comment by bchavez** [comment] 2019-07-05 09:40
Hi Greg,

No problem. Thanks for the reply. Please keep me updated on your progress and findings. Perhaps, when you can, send me a `dotnet --info` dump on your machine too.

**Comment by bchavez** [comment] 2019-07-05 09:47
Also, one more quick question, are you using multiple threads that might be partying on the `operators` variable? There should only be 1 thread accessing a `Faker<T>` at any given time mostly because there's an internal lock when `.Generate` is called to ensure things are sane. See #125 for more info.

**Comment by TheMouster** [comment] 2019-07-05 09:47
Shall do. The only other consideration I can think of is that I’m running in a VM on Windows 7. However everything else is performing at a level that I’d expect.

**Comment by TheMouster** [comment] 2019-07-05 09:56
Threads wise, to my knowledge, no. There’s a fair bit of async/await going on, but not directly surrounding the bogus parts effectively just in the normal EF Core database calls.

Pattern wise I’m doing the following. Read all the records into a hashset. Then creating records using Bogus. Adding the new records to the collection, then, using EF Core bulk extensions, persisting the records back to the database. I’ll chuck up a full sample later tonight after I’ve had a bit of a further play.

**Comment by TheMouster** [comment] 2019-07-05 11:15
dotnet --info as requested.

.NET Core SDK (reflecting any global.json):
 Version:   2.2.101
 Commit:    236713b0b7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x86
 Base Path:   C:\Program Files\dotnet\sdk\2.2.101\

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  1.0.1 [C:\Program Files\dotnet\sdk]
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.10 [C:\Program Files\dotnet\sdk]
  1.1.11 [C:\Program Files\dotnet\sdk]
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.302 [C:\Program Files\dotnet\sdk]
  2.1.400 [C:\Program Files\dotnet\sdk]
  2.1.401 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by TheMouster** [comment] 2019-07-05 14:52
Hi Brian,

You were right. I found the cause of my slow generation. I forgot that when you construct an Operator the last field is a password and the system encrypts it, which is very processor intensive.

Many thanks for your assistance. Profuse apologies for wasting your time.

Cheers

Greg

**Comment by bchavez** [comment] 2019-07-05 22:17
Hi Greg,

No problem. It happens! Thanks for posting the follow-up. I'm sure this information will be very helpful for those coming from Google.

For me, it's never a time waste to hear from users of Bogus so don't ever hesitate to post questions here or Gitter chat. I dedicate whatever time I want to Bogus. Hearing from and helping users of Bogus makes me very happy.

Thanks again for your post,
Brian

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
