### ISSUE TITLE
Based Interface for Fakers

### ISSUE THREAD

**Issue by GrantHoffman** [bchavez/Bogus#301] opened 2020-06-12 16:36 UTC
It would be nice if we could operate on an untyped base interface for fakers.  
This way we can store fakers in a List or Map

e.g FakerMap = new Dictionary<type,  IFakerTInternal>()

please add Generate and add rule methods to an IFakerTInternal  

    IFakerTInternal 
    {
        object Generate(string ruleSet = null)
        void RuleFor(string propertyName, Func<Faker, object, object> rule);
    }

This would make it a lot easier for storing and working with fakers generically

**Comment by bchavez** [comment] 2020-06-13 16:01
Hi Grant,

Thank you for your feedback. However, my initial feeling on this is "maybe". At least, right now, I kinda feel this is a special case. A workaround seems pretty straight forward as shown below:
```csharp
public class User
{
   public string FirstName { get; set; }
   public string LastName { get; set; }
}
public class Pet
{
   public string FirstName{get;set;}
}
```
```csharp
void Main()
{
   var userFaker = new Faker2<User>()
      .RuleFor(b => b.FirstName, f => f.Name.FirstName())
      .RuleFor(b => b.LastName, f => f.Name.LastName())
      as IFaker;

   var petFaker = new Faker2<Pet>()
      .RuleFor(b => b.FirstName, f => f.Name.FirstName())
      as IFaker;
      
   var fakerMap = new Dictionary<Type, IFaker>();
   fakerMap.Add(userFaker.TypeOfT, userFaker);
   fakerMap.Add(petFaker.TypeOfT, petFaker);
   
   foreach(var faker in fakerMap)
   {
      faker.Key.Name.Dump();
      faker.Value.Generate().Dump();
   }
}

public interface IFaker : IFakerTInternal
{
   object Generate(string ruleSet = null);
   void RuleFor(string propertyName, Func<Faker, object, object> rule);
}

public class Faker2<T> : Faker<T>, IFaker where T : class
{
   public void RuleFor(string propertyName, Func<Faker, object, object> rule)
   {
      base.RuleFor(propertyName, rule);
   }

   object IFaker.Generate(string ruleSet)
   {
      return base.Generate(ruleSet);
   }
}
```
![image](https://user-images.githubusercontent.com/478118/84573202-e12dfe00-ad53-11ea-944d-53e18296c77e.png)

My gut feeling on this is more about the semantic use of `Faker<T>`. `Faker<T>`'s main purpose is to be used with `T`. However, I can see where, as in your case, `IFaker` might be helpful for keeping a map of faker objects based on type. At the same time, I have to square your use case with the appropriate use of `Faker<T>`.

The workaround above, in this case, seems straight forward. I'm inclined to close the issue right now, but I will keep this use case in mind if others come across the same issue. Perhaps, if we get enough feedback on this particular issue we'll eventually add a general interface to `Faker<T>`.

Feel free to carry on the discussion after the issue is closed.

**Closed by bchavez** 2020-06-13 16:01 UTC
