### ISSUE TITLE
NullReferenceException on Generate

### ISSUE THREAD

**Issue by feldrim** [bchavez/Bogus#127] opened 2018-02-17 18:47 UTC
I'm using Bogus 22.0.2 on my Asp.Net Core 2.0 project. I have written this simple Bogus code in my static 
Seeder class, which creates fake users using Asp.Net Code Identity:

```
            // Add fake users
            var fakeUsers = new Faker<CrmUser>()
                .RuleFor(u => u.UserName, f => f.Person.UserName)
                .RuleFor(u => u.Email, f => f.Person.Email)
                .RuleFor(u => u.EmailConfirmed, true)
                .GenerateLazy(30).ToList();

            foreach (var user in fakeUsers)
            {
                var result = _userManager.CreateAsync(user, $"{user.UserName}+000").Result;
                if (!result.Succeeded) AddErrors(result);
            }
```

But when Bogus starts to generate (I've tried both `Generate()` and `GenerateLazy()` methods but the results were same) I see this exception on variable `f`:
,
`{System.NullReferenceException: Object reference not set to an instance of an object.`

And the Stack trace looks like this:

```
   at Bogus.Person.Populate()
   at Bogus.Faker.get_Person()
   at Security.AspIdentity.Seeder.<>c.<AddUsers>b__9_1(Faker f) in C:\Users\feldrim\Source\Repos\CRM\CRM\Seeder.cs:line 120
   at Bogus.Faker`1.<>c__DisplayClass25_0`1.<RuleFor>b__0(Faker f, T t)
   at Bogus.Faker`1.PopulateInternal(T instance, String[] ruleSets)
   at Bogus.Faker`1.Generate(String ruleSets)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CRM.Seeder.AddUsers() in C:\Users\feldrim\Source\Repos\CRM\CRM\Seeder.cs:line 119
   at CRM.Seeder.Initialize(IServiceProvider serviceProvider) in C:\Users\Zafer\Source\Repos\CRM\CRM\Seeder.cs:line 34
   at CRM.Program.Main(String[] args) in C:\Users\feldrim\Source\Repos\CRM\CRM\Program.cs:line 41
```

**Comment by bchavez** [comment] 2018-02-17 18:50
Hi @feldrim,

Thanks for reporting the issue. That's pretty strange. Is it repeatable? Do you have a seed value I can use to reproduce the issue?

Thanks,
Brian

**Comment by feldrim** [comment] 2018-02-17 19:25
Thanks for quick reply @bchavez . I havent used a seed but I get the same everytime I ran the code. I've added a seed after your comment but it diddn't affect the result.

But I've managed to use the same code with another class in the same project. The CrmUser class I use is just something to improve, so it's nothing but 3 lines of "nothing":

```
    public class CrmUser : IdentityUser
    {
    }
```

While I had issues about the class above, I haven't got any problems on enumerating (the exception occurs on foreach loop) on this class:

```
    public class CrmPersonnel
    {
        public int Id { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "First name cannot be longer than 50 characters.")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "Last name cannot be longer than 50 characters.")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Full Name")]
        public string FullName => $"{FirstName} {LastName.ToUpper(CultureInfo.CurrentCulture)}";

        [Required]
        [Display(Name = "Application User")]
        public virtual CrmUser UserData { get; set; }
    }
```

I've created 3 demo users first. As you see I map a personnel with a user and the CrmPersonnel class succesfully seeded with 3 handcoded CrmUser records. So I've managed to create 3 CrmPersonnel recorda. It seems it's an issue about the IdentityUser class.

**Comment by bchavez** [comment] 2018-02-17 19:55
Hi @feldrim,

Thanks for the reply. Very strange. I wrote a quick unit test and seems to be passing with flying colors:
```csharp
public class Issue127 : SeededTest
{
   private readonly ITestOutputHelper console;

   public Issue127(ITestOutputHelper console)
   {
      this.console = console;
   }

   [Fact]
   public void Test()
   {
      var fakeUsers = new Faker<CrmUser>()
         .RuleFor(u => u.UserName, f => f.Person.UserName)
         .RuleFor(u => u.Email, f => f.Person.Email)
         .RuleFor(u => u.EmailConfirmed, true);

      var user = fakeUsers.Generate();

      console.Dump(user);

      user.UserName.Should().NotBeNullOrEmpty();
      user.Email.Should().NotBeNullOrEmpty();
      user.EmailConfirmed.Should().BeTrue();
   }


   public class CrmUser
   {
      public string UserName { get; set; }
      public string Email { get; set; }
      public bool EmailConfirmed { get; set; }
   }
}
```

What is the threading environment like for the code you posted above? Are you using multiple threads on **Bogus** anywhere? The only hint I can see a `NullReferenceException` occurring from the stack trace you posted is maybe somehow multiple threads generating at the same time but we have a lock in the `PopulateInternal` method to prevent that from happening. So, I'm a bit puzzled atm.

Could you put together a small/sample zip file that reproduces the issue? I'd ***really*** appreciate it and I'll my best to resolve your issue.

Thanks,
Brian

**Comment by feldrim** [comment] 2018-02-17 20:07
Ok, I've pushed my commits on [this repo](https://github.com/feldrim/Fiver.Security.AspIdentity) so you may experiment on it.

**Comment by bchavez** [comment] 2018-02-17 20:15
Thanks @feldrim, I'll have a look and let you know.

**Comment by bchavez** [comment] 2018-02-21 21:29
Hey @feldrim ,

Hope all is well. I'm going to close this issue for now since I don't have a reliable way to reproduce the issue anymore. Feel free to re-open the issue if you create a unit test that can repo the issue. I'll be happy to take a second look again.

Thanks,
Brian

:evergreen_tree: :crystal_ball: **[PINES - Fate](https://www.youtube.com/watch?v=M2D7lCeVxGs)**

**Closed by bchavez** 2018-02-21 21:29 UTC

**Comment by egemenhalici1** [comment] 2018-06-18 18:45
Hello, 
I am using Bogus  22.1.1 on my Asp.Net Core 2.0 project.

I try to create mail addresses with Bogus.

```
public static IList<Session> CreateSessionSeed(List<Guid> tenantIds)
        {
            List<Session> sessions = new List<Session>();
            tenantIds.ForEach(tenantId =>
            {
                Guid userId = Guid.NewGuid();
                var faker = new Faker();
                var userFullName = faker.Name.FullName();
                var email = faker.Internet.Email();
                var companyName = faker.Company.CompanyName();

                Session sessionFaker = new Faker<Session>()
                    .CustomInstantiator(f => new Session(
                        userId,
                        tenantId,
                        companyName,
                        email,
                        f.Date.Future()
                    )
                );
                sessionFaker.CreateUser(userFullName, email, companyName);
                sessions.Add(sessionFaker);
            });

            return sessions;
        }
```

FullName generator is ok but Email generator is throwing exceptions.

 Exception Message is 

> {System.NullReferenceException:

 >Object reference not set to an instance of an object.
   >at Bogus.DataSet.GetRandomArrayItem(String path, Nullable`1 min, Nullable`1 max)
   >at Bogus.DataSets.Internet.Email(String firstName, String lastName, String provider)
   >at Oplog.Infrastructure.UnitTests.Base.TestDbContext.<>c__DisplayClass18_0.<CreateSessionSeed>b__0(Guid tenantId) in ......

**Comment by bchavez** [comment] 2018-06-18 19:43
Hi @egemenhalici1,

I'm sorry, I can't reproduce your `NullReferenceException` issue with the following unit test:
```csharp
public class Issue127 : SeededTest
{
   private static ITestOutputHelper console;
   public Issue127(ITestOutputHelper console)
   {
      Issue127.console = console;
   }

   [Fact]
   public void test_db_context()
   {
      var tenantIds = Enumerable.Range(1, 50)
         .Select( i => Guid.NewGuid())
         .ToList();

      var sessions = CreateSessionSeed(tenantIds);
      console.Dump(sessions);
   }

   public static IList<Session> CreateSessionSeed(List<Guid> tenantIds)
   {
      List<Session> sessions = new List<Session>();
      tenantIds.ForEach(tenantId =>
         {
            Guid userId = Guid.NewGuid();
            var faker = new Faker();
            var userFullName = faker.Name.FullName();
            var email = faker.Internet.Email();
            var companyName = faker.Company.CompanyName();

            Session sessionFaker = new Faker<Session>()
               .CustomInstantiator(f => new Session(
                     userId,
                     tenantId,
                     companyName,
                     email,
                     f.Date.Future()
                  )
               );
            sessionFaker.CreateUser(userFullName, email, companyName);
            sessions.Add(sessionFaker);
         });

      return sessions;
   }

   public class Session
   {
      public Guid userId;
      public Guid tenantId;
      public string companyName;
      public string email;
      public DateTime dateTime;

      public Session(Guid userId, Guid tenantId, string companyName, string email, DateTime dateTime)
      {
         this.userId = userId;
         this.tenantId = tenantId;
         this.companyName = companyName;
         this.email = email;
         this.dateTime = dateTime;
      }

      public void CreateUser(string userFullName, string email, string companyName)
      {
         console.WriteLine($"{userFullName}, {email}, {companyName}");
      }
   }
}
```
You'll have to provide more information:
* What seed value are you using?
* Can you provide a failing unit test with code I've provided above?
* Can you test it on the latest `Bogus` release `22.1.3`?
* Are you using this code in a multi-threaded enviornment?
* Are there other places where you're using using `Faker<T>` in your app. If so, what and where are they?

Lastly, some helpful advice:
Avoid creating `new Faker<T>` and `new Faker` (facade) objects on the fly in a loop. IMHO, creating `new Faker<Session>` objects and `Faker` facade objects inside the `.ForEach( x => ....` then casting `Faker<Session>` to `Session` is bad practice. Generally, you should setup your `Faker<T>` objects one time only then call `.Generate()` for multiple objects. If the `Faker<T>.Generate()` pattern doesn't work for you then consider just sticking with the `Faker` **facade** pattern to keep it simple. Here is how I would recommend creating `Session`:
```csharp
public static IList<Session> CreateSessionSeed_KeepItSimple(List<Guid> tenantIds)
{
   var faker = new Faker();

   List<Session> sessions = new List<Session>();

   foreach( var tenantId in tenantIds )
   {
      Guid userId = Guid.NewGuid();
      var userFullName = faker.Name.FullName();
      var email = faker.Internet.Email();
      var companyName = faker.Company.CompanyName();

      Session session = new Session(
         userId,
         tenantId,
         companyName,
         email,
         faker.Date.Future());

      session.CreateUser(userFullName, email, companyName);
      sessions.Add(session);
   }
   
   return sessions;
}
```
Hope that helps @egemenhalici1.

Thanks,
Brian
:man: :checkered_flag: ***["Louie Louie, oh no... Me gotta go... Aye-yi-yi-yi, I said"](https://www.youtube.com/watch?v=4V1p1dM3snQ)***

**Comment by egemenhalici1** [comment] 2018-06-20 14:55
Thank you @bchavez .

I cannot find the problem.

But I am using email generator like
`string email = faker.Internet.Email(provider: "domain.com");`
It works . 

Maybe that helps someone.

Thank you,

**Comment by akolodkin** [comment] 2018-09-05 21:01
We had the same issue, issue was gone after we downgraded to 23.0.2

**Comment by bchavez** [comment] 2018-09-05 21:08
Hi @akolodkin ,

Thanks for the report.

* Are you using a seed value? If so, what is the seed?
* Do you have any way to reproduce the issue?
* Were you using `23.0.3` before you downgraded to `23.0.2`?

More information would be helpful so I can squash this bug.

Thanks,
Brian

**Comment by jr-jesse123** [comment] 2021-04-28 12:26
I had the same problem here... it as all working, then all tests begun to fail for nullreference.... after trying somethings out... i just cleaned up the solution, rebuild everything from sctach and that´s working again.. hope it helps...
